In [1]:
import pandas as pd
from pandas import DataFrame

In [2]:
for year in range(2007, 2018):
    data = pd.read_csv("mls-salaries-{0}.csv".format(year))
    df = DataFrame(data, columns=["last_name", "first_name", "guaranteed_compensation"])
    df = df.nlargest(10, "guaranteed_compensation", keep='first')
    df["guaranteed_compensation"] = df["guaranteed_compensation"].astype(int)
    print(df)
    df.to_csv("top10/mls-top10-{0}.csv".format(year), index = False)

       last_name  first_name  guaranteed_compensation
230      Beckham       David                  6500000
3         Blanco  Cuauhtemoc                  2666778
283        Angel  Juan Pablo                  1593750
302        Reyna     Claudio                  1250008
235      Donovan      Landon                   900000
120  De Oliveira    Denilson                   879936
213      Johnson       Eddie                   875000
136         Ruiz      Carlos                   435000
297       Mathis       Clint                   410000
280     Twellman      Taylor                   350008
    last_name  first_name  guaranteed_compensation
21    Beckham       David                  6500000
24     Blanco  Cuauhtemoc                  2666778
119  Gallardo     Marcelo                  1874006
6       Angel  Juan Pablo                  1593750
93    Donovan      Landon                   900000
215     Lopez     Claudio                   820000
103    Emilio     Luciano                   758857
324      Ruiz      Carlos                   460000
131     Gomez   Christian                   430000
83     Davino       Dulio                   400000
     last_name        first_name  guaranteed_compensation
21     Beckham             David                  6500000
28      Blanco        Cuauhtemoc                  2943702
7        Angel        Juan Pablo                  1798000
218  Ljungberg           Fredrik                  1314000
85   de Guzman            Julian                   956350
93     Donovan            Landon                   900000
323  Schelotto  Guillermo Barros                   775000
103     Emilio           Luciano                   758857
188     Joseph           Shalrie                   450000
88   DeRosario            Dwayne                   425750
     last_name      first_name  guaranteed_compensation
28     Beckham           David                  6500000
162      Henry         Thierry                  5600000
239    Marquez          Rafael                  5544000
101    Donovan          Landon                  2127777
11       Angel      Juan Pablo                  1918000
65    Castillo            Nery                  1788060
94   de Guzman          Julian                  1717546
228  Ljungberg         Fredrik                  1314000
243   Martinez  Miguel "Mista"                   987337
41    Boskovic          Branko                   516200
      last_name  first_name  guaranteed_compensation
38      Beckham       David                  6500000
210       Henry     Thierry                  5600000
305     Marquez      Rafael                  4600000
251       Keane      Robbie                  3417243
132     Donovan      Landon                  2300000
123   de Guzman      Julian                  1910746
266  Koevermans       Danny                  1413319
17        Angel  Juan Pablo                  1250000
166      Frings     Torsten                  1113662
207      Hassli        Eric                   900000
      last_name first_name  guaranteed_compensation
207       Henry    Thierry                  5600000
298     Marquez     Rafael                  4600000
39      Beckham      David                  3999999
74       Cahill        Tim                  3624999
254       Keane     Robbie                  3417242
158      Frings    Torsten                  2413666
128     Donovan     Landon                  2400000
124     Di Vaio      Marco                  1937508
117   de Guzman     Julian                  1910746
267  Koevermans      Danny                  1563323
      last_name first_name  guaranteed_compensation
135     Dempsey      Clint                  5038566
227       Henry    Thierry                  4350000
272       Keane     Robbie                  4333333
82       Cahill        Tim                  3625000
142     Donovan     Landon                  2500000
138     Di Vaio      Marco                  1937508
325     Martins    Obafemi                  1725000
288  Koevermans      Danny                  1663323
348      Miller      Kenny                  1124992
355     Montero      Fredy                   856000
    last_name first_name  guaranteed_compensation
268      Kaka        NaN                  7167500
130   Dempsey      Clint                  6695188
71    Bradley    Michael                  6500000
126     Defoe    Jermain                  6180000
138   Donovan     Landon                  4583333
270     Keane     Robbie                  4500000
225     Henry    Thierry                  4350000
85     Cahill        Tim                  3625000
258     Jones   Jermaine                  3252500
133   Di Vaio      Marco                  2600000
      last_name first_name  guaranteed_compensation
258        Kaka        NaN                  7167500
192    Giovinco  Sebastian                  7115555
67      Bradley    Michael                  6500000
190     Gerrard     Steven                  6332504
285     Lampard      Frank                  6000000
136  Dos Santos    Giovani                  5750008
536       Villa      David                  5610000
17     Altidore       Jozy                  4750000
126     Dempsey      Clint                  4605941
263       Keane     Robbie                  4500000
      last_name first_name  guaranteed_compensation
340        Kaka        NaN                  7167500
505    Giovinco  Sebastian                  7115555
500     Bradley    Michael                  6500000
198     Gerrard     Steven                  6132500
284     Lampard      Frank                  6000000
292       Pirlo     Andrea                  5915690
298       Villa      David                  5610000
495    Altidore       Jozy                  4825000
441     Dempsey      Clint                  4605941
196  Dos Santos    Giovani                  4250000
          last_name first_name  guaranteed_compensation
401            Kaka        NaN                  7167500
568        Giovinco  Sebastian                  7115555
560         Bradley    Michael                  6500000
349           Pirlo     Andrea                  5915690
355           Villa      David                  5610000
230      Dos Santos    Giovani                  5500000
55   Schweinsteiger    Bastian                  5400000
556        Altidore       Jozy                  4875000
506         Dempsey      Clint                  3892933
472          Valeri      Diego                  2607500